package com.myntra.apiTests.portalservices.CRMPortalService;

public enum AllServiceHelper {
	VALID_RETURNID,
	VALID_USERNAME,
	VALID_USERNAME_FOR_COUPON,
	SUCCESS_RESP_CODE,
	SUCCESS_STATUS_CODE,
	SUCCESS_STATUS_COUNT,
	
	SUCCESS_STATUS_CODE_COUPON,
	STATUS_TOTAL_COUNT_COUPON,
	
	SUCCESS_STATUS_CODE_COMMENT,
	
	STATUS_CODE_ONHOLD,
	STATUS_TOTAL_COUNT_ONHOLD,
	SUCCESS_ONHOLD_ORDERID,
	
	STATUS_CODE_EXCHANGE,
	SUCCESS_ORDERID_EXCHANGE,
	STATUS_TYPE_EXCHANGE,
	
	SUCCESS_STATUS_TYPE,
	
	//CRM ERP Service Orde Api
	FETCH_SIZE,
	SUCCESS_STATUS_CODE_ERPORDER,
	SUCCESS_RETURNID,
	SUCCESS_ORDERID;
}
