package com.myntra.apiTests.dataproviders;

import java.util.ArrayList;
import java.util.HashMap;

import org.testng.annotations.DataProvider;

public class LgpE2EDP {

	@DataProvider
	  public Object[][] pumpsAction(){
		
		HashMap<String,HashMap<String,String>> data1 = new HashMap<String,HashMap<String,String>>();
		HashMap<String,String> publishAction1 = new HashMap<String,String>();
		
		publishAction1.put("includeLocation", "chennai");
		
		data1.put("publishObject", publishAction1);
		
		return (new Object[][]{{data1}});
		
	}
	
	public ArrayList<HashMap<String,HashMap<String,String>>> dataProviders(String useCase){
		
		ArrayList<HashMap<String,HashMap<String,String>>> data = new ArrayList<HashMap<String,HashMap<String,String>>>();
		switch(useCase){
		case "Location":{
			//case2
			HashMap<String,HashMap<String,String>> data1 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction = new HashMap<String,String>();
			publishAction.put("includeLocation", "bangalore");
			publishAction.put("persona", "unisex");
			HashMap<String,String> feedAction = new HashMap<String,String>();
			feedAction.put("location", "bangalore");
			HashMap<String,String> streamAction = new HashMap<String,String>();
			streamAction.put("location", "bangalore");
			HashMap<String,String> caseName = new HashMap<String,String>();
			caseName.put("scenario", "Location");
			caseName.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data1.put("publishObject", publishAction);
			data1.put("feedsObject", feedAction);
			data1.put("streamsObject", streamAction);
			data1.put("desc", caseName);
			data.add(data1);
			//case3
			/*HashMap<String,HashMap<String,String>> data2 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction2 = new HashMap<String,String>();
			publishAction2.put("includeLocation", "hyderabad,bangalore");
			publishAction2.put("persona", "unisex");
			HashMap<String,String> feedAction2 = new HashMap<String,String>();
			feedAction2.put("location", "hyderabad,bangalore");
			HashMap<String,String> streamAction2 = new HashMap<String,String>();
			streamAction2.put("location", "hyderabad,bangalore");
			HashMap<String,String> caseName2 = new HashMap<String,String>();
			caseName2.put("scenario", "Location");
			caseName2.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data2.put("desc", caseName2);
			data2.put("publishObject", publishAction2);
			data2.put("feedsObject", feedAction2);
			data2.put("streamsObject", streamAction2);
			data.add(data2);
			//case4
			HashMap<String,HashMap<String,String>> data3 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction3 = new HashMap<String,String>();
			publishAction3.put("includeLocation", "punjab");
			publishAction3.put("persona", "unisex");
			HashMap<String,String> feedAction3 = new HashMap<String,String>();
			feedAction3.put("location", "punjab");
			HashMap<String,String> streamAction3 = new HashMap<String,String>();
			streamAction3.put("location", "punjab");
			HashMap<String,String> caseName3 = new HashMap<String,String>();
			caseName3.put("scenario", "Location");
			caseName3.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data3.put("desc", caseName3);
			data3.put("publishObject", publishAction3);
			data3.put("feedsObject", feedAction3);
			data3.put("streamsObject", streamAction3);
			data.add(data3);
			//case5
			HashMap<String,HashMap<String,String>> data4 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction4 = new HashMap<String,String>();
			publishAction4.put("includeLocation", "punjab,karnataka");
			publishAction4.put("persona", "unisex");
			HashMap<String,String> feedAction4 = new HashMap<String,String>();
			feedAction4.put("location", "punjab,karnataka");
			HashMap<String,String> streamAction4 = new HashMap<String,String>();
			streamAction4.put("location", "punjab,karnataka");
			HashMap<String,String> caseName4 = new HashMap<String,String>();
			caseName4.put("scenario", "Location");
			caseName4.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data4.put("desc", caseName4);
			data4.put("publishObject", publishAction4);
			data4.put("feedsObject", feedAction4);
			data4.put("streamsObject", streamAction4);
			data.add(data4);
			//case6
			HashMap<String,HashMap<String,String>> data5 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction5 = new HashMap<String,String>();
			publishAction5.put("includeLocation", "chennai,karnataka");
			publishAction5.put("persona", "unisex");
			HashMap<String,String> feedAction5 = new HashMap<String,String>();
			feedAction5.put("location", "chennai,karnataka");
			HashMap<String,String> streamAction5 = new HashMap<String,String>();
			streamAction5.put("location", "chennai,karnataka");
			HashMap<String,String> caseName5 = new HashMap<String,String>();
			caseName5.put("scenario", "Location");
			caseName5.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data5.put("desc", caseName5);
			data5.put("publishObject", publishAction5);
			data5.put("streamsObject", streamAction5);
			data.add(data5);
			//case7
			HashMap<String,HashMap<String,String>> data6 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction6 = new HashMap<String,String>();
			publishAction6.put("excludeLocation", "chennai");
			publishAction6.put("persona", "unisex");
			HashMap<String,String> feedAction6 = new HashMap<String,String>();
			feedAction6.put("location", "chennai");
			HashMap<String,String> streamAction6 = new HashMap<String,String>();
			streamAction6.put("location", "chennai");
			HashMap<String,String> caseName6 = new HashMap<String,String>();
			caseName6.put("scenario", "Location");
			caseName6.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data6.put("desc", caseName6);
			data6.put("publishObject", publishAction6);
			data6.put("feedsObject", feedAction6);
			data6.put("streamsObject", streamAction6);
			data.add(data6);
			//case8
			HashMap<String,HashMap<String,String>> data7 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction7 = new HashMap<String,String>();
			publishAction7.put("excludeLocation", "chennai,hyderabad");
			publishAction7.put("persona", "unisex");
			HashMap<String,String> feedAction7 = new HashMap<String,String>();
			feedAction7.put("location", "chennai");
			HashMap<String,String> streamAction7 = new HashMap<String,String>();
			streamAction7.put("location", "chennai");
			HashMap<String,String> caseName7 = new HashMap<String,String>();
			caseName7.put("scenario", "Location");
			caseName7.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data7.put("desc", caseName7);
			data7.put("publishObject", publishAction7);
			data7.put("feedsObject", feedAction7);
			data7.put("streamsObject", streamAction7);
			data.add(data7);
			//case9
			HashMap<String,HashMap<String,String>> data8 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction8 = new HashMap<String,String>();
			publishAction8.put("excludeLocation", "punjab");
			publishAction8.put("persona", "unisex");
			HashMap<String,String> feedAction8 = new HashMap<String,String>();
			feedAction8.put("location", "punjab");
			HashMap<String,String> streamAction8 = new HashMap<String,String>();
			streamAction8.put("location", "punjab");
			HashMap<String,String> caseName8 = new HashMap<String,String>();
			caseName8.put("scenario", "Location");
			caseName8.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data8.put("desc", caseName8);
			data8.put("publishObject", publishAction8);
			data8.put("feedsObject", feedAction8);
			data8.put("streamsObject", streamAction8);
			data.add(data8);
			//case10
			HashMap<String,HashMap<String,String>> data9 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction9 = new HashMap<String,String>();
			publishAction9.put("excludeLocation", "punjab,karnataka");
			publishAction9.put("persona", "unisex");
			HashMap<String,String> feedAction9 = new HashMap<String,String>();
			feedAction9.put("location", "punjab,karnataka");
			HashMap<String,String> streamAction9 = new HashMap<String,String>();
			streamAction9.put("location", "punjab,karnataka");
			HashMap<String,String> caseName9 = new HashMap<String,String>();
			caseName9.put("scenario", "Location");
			caseName9.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data9.put("desc", caseName9);
			data9.put("publishObject", publishAction9);
			data9.put("feedsObject", feedAction9);
			data9.put("streamsObject", streamAction9);
			data.add(data9);*/
			//case11
			HashMap<String,HashMap<String,String>> data10 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction10 = new HashMap<String,String>();
			publishAction10.put("excludeLocation", "punjab,chennai");
			publishAction10.put("persona", "unisex");
			HashMap<String,String> feedAction10 = new HashMap<String,String>();
			feedAction10.put("location", "punjab,chennai");
			HashMap<String,String> streamAction10 = new HashMap<String,String>();
			streamAction10.put("location", "punjab,chennai");
			HashMap<String,String> caseName10 = new HashMap<String,String>();
			caseName10.put("scenario", "Location");
			caseName10.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data10.put("desc", caseName10);
			data10.put("publishObject", publishAction10);
			data10.put("feedsObject", feedAction10);
			data10.put("streamsObject", streamAction10);
			data.add(data10);
			
			//case12
			HashMap<String,HashMap<String,String>> data11 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction11 = new HashMap<String,String>();
			publishAction11.put("excludeLocation", "chennai");
			publishAction11.put("includeLocation", "hyderabad");
			publishAction11.put("persona", "unisex");
			HashMap<String,String> feedAction11 = new HashMap<String,String>();
			feedAction11.put("location", "chennai,hyderabad");
			HashMap<String,String> streamAction11 = new HashMap<String,String>();
			streamAction11.put("location", "chennai,hyderabad");
			HashMap<String,String> caseName11 = new HashMap<String,String>();
			caseName11.put("scenario", "Location");
			caseName11.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data11.put("desc", caseName11);
			data11.put("publishObject", publishAction11);
			data11.put("feedsObject", feedAction11);
			data11.put("streamsObject", streamAction11);
			data.add(data11);
			//case14
			HashMap<String,HashMap<String,String>> data12 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction12 = new HashMap<String,String>();
			publishAction12.put("includeLocation", "chennai");
			publishAction12.put("persona", "men");
			HashMap<String,String> feedAction12 = new HashMap<String,String>();
			feedAction12.put("location", "chennai");
			HashMap<String,String> streamAction12 = new HashMap<String,String>();
			streamAction12.put("location", "chennai");
			HashMap<String,String> caseName12 = new HashMap<String,String>();
			caseName12.put("scenario", "Location");
			caseName12.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data12.put("desc", caseName12);
			data12.put("publishObject", publishAction12);
			data12.put("feedsObject", feedAction12);
			data12.put("streamsObject", streamAction12);
			data.add(data12);
			//case15
			HashMap<String,HashMap<String,String>> data13 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction13 = new HashMap<String,String>();
			publishAction13.put("includeLocation", "chennai,hyderabad");
			publishAction13.put("persona", "men");
			HashMap<String,String> feedAction13 = new HashMap<String,String>();
			feedAction13.put("location", "chennai,hyderabad");
			HashMap<String,String> streamAction13 = new HashMap<String,String>();
			streamAction13.put("location", "chennai,hyderabad");
			HashMap<String,String> caseName13 = new HashMap<String,String>();
			caseName13.put("scenario", "Location");
			caseName13.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data13.put("desc", caseName13);
			data13.put("publishObject", publishAction13);
			data13.put("feedsObject", feedAction13);
			data13.put("streamsObject", streamAction13);
			data.add(data13);
			//case16
			HashMap<String,HashMap<String,String>> data14 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction14 = new HashMap<String,String>();
			publishAction14.put("includeLocation", "karnataka");
			publishAction14.put("persona", "men");
			HashMap<String,String> feedAction14 = new HashMap<String,String>();
			feedAction14.put("location", "karnataka");
			HashMap<String,String> streamAction14 = new HashMap<String,String>();
			streamAction14.put("location", "karnataka");
			HashMap<String,String> caseName14 = new HashMap<String,String>();
			caseName14.put("scenario", "Location");
			caseName14.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data14.put("desc", caseName14);
			data14.put("publishObject", publishAction14);
			data14.put("feedsObject", feedAction14);
			data14.put("streamsObject", streamAction14);
			data.add(data14);
			//case17
			HashMap<String,HashMap<String,String>> data15 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction15 = new HashMap<String,String>();
			publishAction15.put("includeLocation", "punjab,karnataka");
			publishAction15.put("persona", "men");
			HashMap<String,String> feedAction15 = new HashMap<String,String>();
			feedAction15.put("location", "punjab,karnataka");
			HashMap<String,String> streamAction15 = new HashMap<String,String>();
			streamAction15.put("location", "punjab,karnataka");
			HashMap<String,String> caseName15 = new HashMap<String,String>();
			caseName15.put("scenario", "Location");
			caseName15.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data11.put("desc", caseName15);
			data15.put("publishObject", publishAction15);
			data15.put("feedsObject", feedAction15);
			data15.put("streamsObject", streamAction15);
			data.add(data15);
			//case18
			/*HashMap<String,HashMap<String,String>> data16 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction16 = new HashMap<String,String>();
			publishAction16.put("includeLocation", "punjab,karnataka");
			publishAction16.put("persona", "men");
			HashMap<String,String> feedAction16 = new HashMap<String,String>();
			feedAction16.put("location", "punjab,karnataka");
			HashMap<String,String> streamAction16 = new HashMap<String,String>();
			streamAction16.put("location", "punjab,karnataka");
			HashMap<String,String> caseName16 = new HashMap<String,String>();
			caseName16.put("scenario", "Location");
			caseName16.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data16.put("desc", caseName16);
			data16.put("publishObject", publishAction16);
			data16.put("feedsObject", feedAction16);
			data16.put("streamsObject", streamAction16);
			data.add(data16);
			//case19
			HashMap<String,HashMap<String,String>> data17 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction17 = new HashMap<String,String>();
			publishAction17.put("excludeLocation", "bangalore");
			publishAction17.put("persona", "men");
			HashMap<String,String> feedAction17 = new HashMap<String,String>();
			feedAction17.put("location", "bangalore");
			HashMap<String,String> streamAction17 = new HashMap<String,String>();
			streamAction17.put("location", "bangalore");
			HashMap<String,String> caseName17 = new HashMap<String,String>();
			caseName17.put("scenario", "Location");
			caseName17.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data17.put("desc", caseName17);
			data17.put("publishObject", publishAction17);
			data17.put("feedsObject", feedAction17);
			data17.put("streamsObject", streamAction17);
			data.add(data17);
			//case20
			HashMap<String,HashMap<String,String>> data18 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction18 = new HashMap<String,String>();
			publishAction18.put("excludeLocation", "hyderabad,bangalore");
			publishAction18.put("persona", "men");
			HashMap<String,String> feedAction18 = new HashMap<String,String>();
			feedAction18.put("location", "hyderabad,bangalore");
			HashMap<String,String> streamAction18 = new HashMap<String,String>();
			streamAction18.put("location", "hyderabad,bangalore");
			HashMap<String,String> caseName18 = new HashMap<String,String>();
			caseName18.put("scenario", "Location");
			caseName18.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data18.put("desc", caseName18);
			data18.put("publishObject", publishAction18);
			data18.put("feedsObject", feedAction18);
			data18.put("streamsObject", streamAction18);
			data.add(data18);
			//case21
			HashMap<String,HashMap<String,String>> data19 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction19 = new HashMap<String,String>();
			publishAction19.put("excludeLocation", "punjab");
			publishAction19.put("persona", "men");
			HashMap<String,String> feedAction19 = new HashMap<String,String>();
			feedAction19.put("location", "punjab");
			HashMap<String,String> streamAction19 = new HashMap<String,String>();
			streamAction19.put("location", "punjab");
			HashMap<String,String> caseName19 = new HashMap<String,String>();
			caseName19.put("scenario", "Location");
			caseName19.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data19.put("desc", caseName19);
			data19.put("publishObject", publishAction19);
			data19.put("feedsObject", feedAction19);
			data19.put("streamsObject", streamAction19);
			data.add(data19);
			//case22
			HashMap<String,HashMap<String,String>> data20 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction20 = new HashMap<String,String>();
			publishAction20.put("excludeLocation", "punjab,andhra pradesh");
			publishAction20.put("persona", "men");
			HashMap<String,String> feedAction20 = new HashMap<String,String>();
			feedAction20.put("location", "punjab,andhra pradesh");
			HashMap<String,String> streamAction20 = new HashMap<String,String>();
			streamAction20.put("location", "punjab,andhra pradesh");
			HashMap<String,String> caseName20 = new HashMap<String,String>();
			caseName20.put("scenario", "Location");
			caseName20.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data20.put("desc", caseName20);
			data20.put("publishObject", publishAction20);
			data20.put("feedsObject", feedAction20);
			data20.put("streamsObject", streamAction20);
			data.add(data20);
			//case23
			HashMap<String,HashMap<String,String>> data21 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction21 = new HashMap<String,String>();
			publishAction21.put("excludeLocation", "punjab,bangalore");
			publishAction21.put("persona", "men");
			HashMap<String,String> feedAction21 = new HashMap<String,String>();
			feedAction21.put("location", "punjab,bangalore");
			HashMap<String,String> streamAction21 = new HashMap<String,String>();
			streamAction21.put("location", "punjab,bangalore");
			HashMap<String,String> caseName21 = new HashMap<String,String>();
			caseName21.put("scenario", "Location");
			caseName21.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data21.put("desc", caseName21);
			data21.put("publishObject", publishAction21);
			data21.put("feedsObject", feedAction21);
			data21.put("streamsObject", streamAction21);
			data.add(data21);
			//case24
			HashMap<String,HashMap<String,String>> data22 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction22 = new HashMap<String,String>();
			publishAction22.put("includeLocation", "punjab");
			publishAction22.put("excludeLocation", "karnataka");
			publishAction22.put("persona", "men");
			HashMap<String,String> feedAction22 = new HashMap<String,String>();
			feedAction22.put("location", "punjab,bangalore");
			HashMap<String,String> streamAction22 = new HashMap<String,String>();
			streamAction22.put("location", "punjab,bangalore");
			HashMap<String,String> caseName22 = new HashMap<String,String>();
			caseName22.put("scenario", "Location");
			caseName22.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data22.put("desc", caseName22);
			data22.put("publishObject", publishAction22);
			data22.put("feedsObject", feedAction22);
			data22.put("streamsObject", streamAction22);
			data.add(data22);
			//case26
			HashMap<String,HashMap<String,String>> data23 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction23 = new HashMap<String,String>();
			publishAction23.put("includeLocation", "delhi");
			publishAction23.put("persona", "women");
			HashMap<String,String> feedAction23 = new HashMap<String,String>();
			feedAction23.put("location", "delhi");
			HashMap<String,String> streamAction23 = new HashMap<String,String>();
			streamAction23.put("location", "delhi");
			HashMap<String,String> caseName23 = new HashMap<String,String>();
			caseName23.put("scenario", "Location");
			caseName23.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data23.put("desc", caseName23);
			data23.put("publishObject", publishAction23);
			data23.put("feedsObject", feedAction23);
			data23.put("streamsObject", streamAction23);
			data.add(data23);
			//case27
			HashMap<String,HashMap<String,String>> data24 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction24 = new HashMap<String,String>();
			publishAction24.put("includeLocation", "delhi,bangalore");
			publishAction24.put("persona", "women");
			HashMap<String,String> feedAction24 = new HashMap<String,String>();
			feedAction24.put("location", "delhi,bangalore");
			HashMap<String,String> streamAction24 = new HashMap<String,String>();
			streamAction24.put("location", "delhi,bangalore");
			HashMap<String,String> caseName24 = new HashMap<String,String>();
			caseName24.put("scenario", "Location");
			caseName24.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data24.put("desc", caseName24);
			data24.put("publishObject", publishAction24);
			data24.put("feedsObject", feedAction24);
			data24.put("streamsObject", streamAction24);
			data.add(data24);
			//case28
			HashMap<String,HashMap<String,String>> data25 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction25 = new HashMap<String,String>();
			publishAction25.put("includeLocation", "punjab");
			publishAction25.put("persona", "women");
			HashMap<String,String> feedAction25 = new HashMap<String,String>();
			feedAction25.put("location", "punjab");
			HashMap<String,String> streamAction25 = new HashMap<String,String>();
			streamAction25.put("location", "punjab");
			HashMap<String,String> caseName25 = new HashMap<String,String>();
			caseName25.put("scenario", "Location");
			caseName25.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data25.put("desc", caseName25);
			data25.put("publishObject", publishAction25);
			data25.put("feedsObject", feedAction25);
			data25.put("streamsObject", streamAction25);
			data.add(data25);
			//case29
			HashMap<String,HashMap<String,String>> data26 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction26 = new HashMap<String,String>();
			publishAction26.put("includeLocation", "punjab,karnataka");
			publishAction26.put("persona", "women");
			HashMap<String,String> feedAction26 = new HashMap<String,String>();
			feedAction26.put("location", "punjab,karnataka");
			HashMap<String,String> streamAction26 = new HashMap<String,String>();
			streamAction26.put("location", "punjab,karnataka");
			HashMap<String,String> caseName26 = new HashMap<String,String>();
			caseName26.put("scenario", "Location");
			caseName26.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data26.put("desc", caseName26);
			data26.put("publishObject", publishAction26);
			data26.put("feedsObject", feedAction26);
			data26.put("streamsObject", streamAction26);
			data.add(data26);
			//case30
			HashMap<String,HashMap<String,String>> data27 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction27 = new HashMap<String,String>();
			publishAction27.put("includeLocation", "punjab,chennai");
			publishAction27.put("persona", "women");
			HashMap<String,String> feedAction27 = new HashMap<String,String>();
			feedAction27.put("location", "punjab,chennai");
			HashMap<String,String> streamAction27 = new HashMap<String,String>();
			streamAction27.put("location", "punjab,chennai");
			HashMap<String,String> caseName27 = new HashMap<String,String>();
			caseName27.put("scenario", "Location");
			caseName27.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data27.put("desc", caseName27);
			data27.put("publishObject", publishAction27);
			data27.put("feedsObject", feedAction27);
			data27.put("streamsObject", streamAction27);
			data.add(data27);
			//case31
			HashMap<String,HashMap<String,String>> data28 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction28 = new HashMap<String,String>();
			publishAction28.put("excludeLocation", "chennai");
			publishAction28.put("persona", "women");
			HashMap<String,String> feedAction28 = new HashMap<String,String>();
			feedAction28.put("location", "chennai");
			HashMap<String,String> streamAction28 = new HashMap<String,String>();
			streamAction28.put("location", "chennai");
			HashMap<String,String> caseName28 = new HashMap<String,String>();
			caseName28.put("scenario", "Location");
			caseName28.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data28.put("desc", caseName28);
			data28.put("publishObject", publishAction28);
			data28.put("feedsObject", feedAction28);
			data28.put("streamsObject", streamAction28);
			data.add(data28);
			//case32
			HashMap<String,HashMap<String,String>> data29 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction29 = new HashMap<String,String>();
			publishAction29.put("excludeLocation", "chennai,bangalore");
			publishAction29.put("persona", "women");
			HashMap<String,String> feedAction29 = new HashMap<String,String>();
			feedAction29.put("location", "chennai,bangalore");
			HashMap<String,String> streamAction29 = new HashMap<String,String>();
			streamAction29.put("location", "chennai,bangalore");
			HashMap<String,String> caseName29 = new HashMap<String,String>();
			caseName29.put("scenario", "Location");
			caseName29.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data29.put("desc", caseName29);
			data29.put("publishObject", publishAction29);
			data29.put("feedsObject", feedAction29);
			data29.put("streamsObject", streamAction29);
			data.add(data29);
			//case33
			HashMap<String,HashMap<String,String>> data30 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction30 = new HashMap<String,String>();
			publishAction30.put("excludeLocation", "karnataka");
			publishAction30.put("persona", "women");
			HashMap<String,String> feedAction30 = new HashMap<String,String>();
			feedAction30.put("location", "karnataka");
			HashMap<String,String> streamAction30 = new HashMap<String,String>();
			streamAction30.put("location", "karnataka");
			HashMap<String,String> caseName30 = new HashMap<String,String>();
			caseName30.put("scenario", "Location");
			caseName30.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data30.put("desc", caseName30);
			data30.put("publishObject", publishAction30);
			data30.put("feedsObject", feedAction30);
			data30.put("streamsObject", streamAction30);
			data.add(data30);
			//case34
			HashMap<String,HashMap<String,String>> data31 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction31 = new HashMap<String,String>();
			publishAction31.put("excludeLocation", "karnataka");
			publishAction31.put("persona", "women");
			HashMap<String,String> feedAction31 = new HashMap<String,String>();
			feedAction31.put("location", "karnataka");
			HashMap<String,String> streamAction31 = new HashMap<String,String>();
			streamAction31.put("location", "karnataka");
			HashMap<String,String> caseName31 = new HashMap<String,String>();
			caseName31.put("scenario", "Location");
			caseName31.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data31.put("desc", caseName31);
			data31.put("publishObject", publishAction31);
			data31.put("feedsObject", feedAction31);
			data31.put("streamsObject", streamAction31);
			data.add(data31);
			//case35
			HashMap<String,HashMap<String,String>> data32 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction32 = new HashMap<String,String>();
			publishAction32.put("excludeLocation", "chennai,karnataka");
			publishAction32.put("persona", "women");
			HashMap<String,String> feedAction32 = new HashMap<String,String>();
			feedAction32.put("location", "chennai,karnataka");
			HashMap<String,String> streamAction32 = new HashMap<String,String>();
			streamAction32.put("location", "chennai,karnataka");
			HashMap<String,String> caseName32 = new HashMap<String,String>();
			caseName32.put("scenario", "Location");
			caseName32.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data32.put("desc", caseName32);
			data32.put("publishObject", publishAction32);
			data32.put("feedsObject", feedAction32);
			data32.put("streamsObject", streamAction32);
			data.add(data32);
			//case36
			HashMap<String,HashMap<String,String>> data33 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction33 = new HashMap<String,String>();
			publishAction33.put("includeLocation", "punjab");
			publishAction33.put("excludeLocation", "karnataka");
			publishAction33.put("persona", "women");
			HashMap<String,String> feedAction33 = new HashMap<String,String>();
			feedAction33.put("location", "punjab,karnataka");
			HashMap<String,String> streamAction33 = new HashMap<String,String>();
			streamAction33.put("location", "punjab,karnataka");
			HashMap<String,String> caseName33 = new HashMap<String,String>();
			caseName33.put("scenario", "Location");
			caseName33.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data33.put("desc", caseName33);
			data33.put("publishObject", publishAction33);
			data33.put("feedsObject", feedAction33);
			data33.put("streamsObject", streamAction33);
			data.add(data33);
			//case37
			HashMap<String,HashMap<String,String>> data34 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction34 = new HashMap<String,String>();
			publishAction34.put("includeLocation", "chennai");
			publishAction34.put("excludeLocation", "chennai");
			publishAction34.put("persona", "unisex");
			HashMap<String,String> feedAction34 = new HashMap<String,String>();
			feedAction34.put("location", "chennai");
			HashMap<String,String> streamAction34 = new HashMap<String,String>();
			streamAction34.put("location", "chennai");
			HashMap<String,String> caseName34 = new HashMap<String,String>();
			caseName34.put("scenario", "Location");
			caseName34.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data34.put("desc", caseName34);
			data34.put("publishObject", publishAction34);
			data34.put("feedsObject", feedAction34);
			data34.put("streamsObject", streamAction34);
			data.add(data34);
			//case38
			HashMap<String,HashMap<String,String>> data35 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction35 = new HashMap<String,String>();
			publishAction35.put("includeLocation", "bangalore");
			publishAction35.put("excludeLocation", "karnataka");
			publishAction35.put("persona", "unisex");
			HashMap<String,String> feedAction35 = new HashMap<String,String>();
			feedAction35.put("location", "bangalore,karnataka");
			HashMap<String,String> streamAction35 = new HashMap<String,String>();
			streamAction35.put("location", "bangalore,karnataka");
			HashMap<String,String> caseName35 = new HashMap<String,String>();
			caseName35.put("scenario", "Location");
			caseName35.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data35.put("desc", caseName35);
			data35.put("publishObject", publishAction35);
			data35.put("feedsObject", feedAction35);
			data35.put("streamsObject", streamAction35);
			data.add(data35);
			//case39
			HashMap<String,HashMap<String,String>> data36 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction36 = new HashMap<String,String>();
			publishAction36.put("includeLocation", "karnataka");
			publishAction36.put("excludeLocation", "bangalore");
			publishAction36.put("persona", "unisex");
			HashMap<String,String> feedAction36 = new HashMap<String,String>();
			feedAction36.put("location", "bangalore,karnataka");
			HashMap<String,String> streamAction36 = new HashMap<String,String>();
			streamAction36.put("location", "bangalore,karnataka");
			HashMap<String,String> caseName36 = new HashMap<String,String>();
			caseName36.put("scenario", "Location");
			caseName36.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data36.put("desc", caseName36);
			data36.put("publishObject", publishAction36);
			data36.put("feedsObject", feedAction36);
			data36.put("streamsObject", streamAction36);
			data.add(data36);
			//case 40
			HashMap<String,HashMap<String,String>> data37 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction37 = new HashMap<String,String>();
			publishAction37.put("includeLocation", "chennai");
			publishAction37.put("excludeLocation", "chennai");
			publishAction37.put("persona", "men");
			HashMap<String,String> feedAction37 = new HashMap<String,String>();
			feedAction37.put("location", "chennai");
			HashMap<String,String> streamAction37 = new HashMap<String,String>();
			streamAction37.put("location", "chennai");
			HashMap<String,String> caseName37 = new HashMap<String,String>();
			caseName37.put("scenario", "Location");
			caseName37.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data37.put("desc", caseName37);
			data37.put("publishObject", publishAction37);
			data37.put("feedsObject", feedAction37);
			data37.put("streamsObject", streamAction37);
			data.add(data37);
			//case 41
			HashMap<String,HashMap<String,String>> data38 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction38 = new HashMap<String,String>();
			publishAction38.put("includeLocation", "bangalore");
			publishAction38.put("excludeLocation", "karnataka");
			publishAction38.put("persona", "men");
			HashMap<String,String> feedAction38 = new HashMap<String,String>();
			feedAction38.put("location", "bangalore,karnataka");
			HashMap<String,String> streamAction38 = new HashMap<String,String>();
			streamAction38.put("location", "bangalore,karnataka");
			HashMap<String,String> caseName38 = new HashMap<String,String>();
			caseName38.put("scenario", "Location");
			caseName38.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data38.put("desc", caseName38);
			data38.put("publishObject", publishAction38);
			data38.put("feedsObject", feedAction38);
			data38.put("streamsObject", streamAction38);
			data.add(data38);
			//case42
			HashMap<String,HashMap<String,String>> data39 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction39 = new HashMap<String,String>();
			publishAction39.put("includeLocation", "karnataka");
			publishAction39.put("excludeLocation", "bangalore");
			publishAction39.put("persona", "men");
			HashMap<String,String> feedAction39 = new HashMap<String,String>();
			feedAction39.put("location", "bangalore,karnataka");
			HashMap<String,String> streamAction39 = new HashMap<String,String>();
			streamAction39.put("location", "bangalore,karnataka");
			HashMap<String,String> caseName39 = new HashMap<String,String>();
			caseName39.put("scenario", "Location");
			caseName39.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data39.put("desc", caseName39);
			data39.put("publishObject", publishAction39);
			data39.put("feedsObject", feedAction39);
			data39.put("streamsObject", streamAction39);
			data.add(data39);
			//case43
			HashMap<String,HashMap<String,String>> data40 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction40 = new HashMap<String,String>();
			publishAction40.put("includeLocation", "chennai");
			publishAction40.put("excludeLocation", "chennai");
			publishAction40.put("persona", "women");
			HashMap<String,String> feedAction40 = new HashMap<String,String>();
			feedAction40.put("location", "chennai");
			HashMap<String,String> streamAction40 = new HashMap<String,String>();
			streamAction40.put("location", "chennai");
			HashMap<String,String> caseName40 = new HashMap<String,String>();
			caseName40.put("scenario", "Location");
			caseName40.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data40.put("desc", caseName40);
			data40.put("publishObject", publishAction40);
			data40.put("feedsObject", feedAction40);
			data40.put("streamsObject", streamAction40);
			data.add(data40);
			//case44
			HashMap<String,HashMap<String,String>> data41 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction41 = new HashMap<String,String>();
			publishAction41.put("includeLocation", "bangalore");
			publishAction41.put("excludeLocation", "karnataka");
			publishAction41.put("persona", "women");
			HashMap<String,String> feedAction41 = new HashMap<String,String>();
			feedAction41.put("location", "bangalore,karnataka");
			HashMap<String,String> streamAction41 = new HashMap<String,String>();
			streamAction41.put("location", "bangalore,karnataka");
			HashMap<String,String> caseName41 = new HashMap<String,String>();
			caseName41.put("scenario", "Location");
			caseName41.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data41.put("desc", caseName41);
			data41.put("publishObject", publishAction41);
			data41.put("feedsObject", feedAction41);
			data41.put("streamsObject", streamAction41);
			data.add(data41);
			//case45
			HashMap<String,HashMap<String,String>> data42 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction42 = new HashMap<String,String>();
			publishAction42.put("includeLocation", "karnataka");
			publishAction42.put("excludeLocation", "bangalore");
			publishAction42.put("persona", "women");
			HashMap<String,String> feedAction42 = new HashMap<String,String>();
			feedAction42.put("location", "bangalore,karnataka");
			HashMap<String,String> streamAction42 = new HashMap<String,String>();
			streamAction42.put("location", "bangalore,karnataka");
			HashMap<String,String> caseName42 = new HashMap<String,String>();
			caseName42.put("scenario", "Location");
			caseName42.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data42.put("desc", caseName42);
			data42.put("publishObject", publishAction42);
			data42.put("feedsObject", feedAction42);
			data42.put("streamsObject", streamAction42);
			data.add(data42);
			//case 1
			HashMap<String,HashMap<String,String>> data43 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction43 = new HashMap<String,String>();
			publishAction43.put("persona", "unisex");
			data43.put("publishObject", publishAction43);
			HashMap<String,String> caseName43 = new HashMap<String,String>();
			caseName43.put("scenario", "Location");
			caseName43.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data43.put("desc", caseName43);
			data.add(data43);
			//case 13
			HashMap<String,HashMap<String,String>> data44 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction44 = new HashMap<String,String>();
			publishAction44.put("persona", "men");
			HashMap<String,String> caseName44 = new HashMap<String,String>();
			caseName44.put("scenario", "Location");
			caseName44.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data44.put("desc", caseName44);
			data44.put("publishObject", publishAction44);
			data.add(data44);
			//case 25
			HashMap<String,HashMap<String,String>> data45 = new HashMap<String,HashMap<String,String>>();
			HashMap<String,String> publishAction45 = new HashMap<String,String>();
			publishAction45.put("persona", "women");
			HashMap<String,String> caseName45 = new HashMap<String,String>();
			caseName45.put("scenario", "Location");
			caseName45.put("description", "Case to validate that an object having include location is displayed if that location is given in feeds or streams call");
			data45.put("desc", caseName45);
			data45.put("publishObject", publishAction45);
			data.add(data45);*/
		}
		}
		return data;
	}
}
