
package com.myntra.apiTests.dataproviders;

import com.myntra.apiTests.portalservices.checkoutservice.CheckoutServiceConstants;
import com.myntra.apiTests.portalservices.commons.CommonUtils;
import org.testng.ITestContext;
import org.testng.annotations.DataProvider;

import com.myntra.apiTests.portalservices.checkoutservice.CheckoutDataProviderEnum;
import com.myntra.lordoftherings.Toolbox;

public class WishListServiceDP extends CommonUtils implements CheckoutServiceConstants
{
	String environment;
	
	public WishListServiceDP()
	{
		if(System.getenv(CheckoutDataProviderEnum.ENVIRONMENT.name()) == null)
			environment = CONFIGURATION.GetTestEnvironemnt().toString();
		else
			environment = System.getenv(CheckoutDataProviderEnum.ENVIRONMENT.name());
	}
	

	@DataProvider
	public Object[][] WishListServiceDP_moveToWishListDataProvider_validateAPIResponse(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7 ,arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_moveToWishListDataProvider_positiveCases(ITestContext testContext)
	{

		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6 , arr7, arr8};
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_operationFetchWishListDataProvider_validateAPIResponse(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_operationFetchWishListDataProvider_positiveCases(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_addItemToWishListUsingSkuIdDataProvider_validateAPIResponse(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_addItemToWishListUsingSkuIdDataProvider_positiveCases(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_addItemToWishListUsingStyleIdDataProvider_validateAPIResponse(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };

		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_addItemToWishListUsingStyleIdDataProvider_positiveCases(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE,
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_STATUS_CODE,
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_updateItemInWishListDataProvider_validateAPIResponse(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, PROD_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, FOX7_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, FUNC_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, PERF_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, PROD_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, FOX7_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, FUNC_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, PERF_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_updateItemInWishListDataProvider_positiveCases(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, PROD_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, FOX7_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, FUNC_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_STATUS_CODE,
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, PERF_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_STATUS_CODE,
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, PROD_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, FOX7_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_STATUS_CODE,
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, FUNC_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, PERF_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_STATUS_CODE, 
				SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_removeItemFromWishListDataProvider_validateAPIResponse(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_removeItemFromWishListDataProvider_positiveCases(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_moveItemToCartDataProvider_validateAPIResponse(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_moveItemToCartDataProvider_positiveCases(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, SUCCESS_STATUS_CODE, SUCCESS_STATUS_MSG, SUCCESS_STATUS_TYPE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8};
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	

	@DataProvider
	public Object[][] WishListServiceDP_moveToWishListDataProvider_verifyResponseDataNodesUsingSchemaValidations(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7 ,arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_addItemToWishListUsingSkuIdDataProvider_verifyResponseDataNodesUsingSchemaValidations(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_addItemToWishListUsingStyleIdDataProvider_verifyResponseDataNodesUsingSchemaValidations(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, PROD_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, FOX7_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, FUNC_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, PERF_WL_ADD_ITEM_QTY, ADD_OPERATION, SUCCESS_RESPONSE_CODE };

		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_updateItemInWishListDataProvider_verifyResponseDataNodesUsingSchemaValidations(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, PROD_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, FOX7_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, FUNC_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, PERF_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, PROD_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, FOX7_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, FUNC_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, PERF_WL_UPD_ITEM_QTY, UPDATE_OPERATION, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_removeItemFromWishListDataProvider_verifyResponseDataNodesUsingSchemaValidations(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, DELETE_OPERATION, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	@DataProvider
	public Object[][] WishListServiceDP_moveItemToCartDataProvider_verifyResponseDataNodesUsingSchemaValidations(ITestContext testContext)
	{
		String[] arr1 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME1, PROD_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr2 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME1, FOX7_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr3 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME1, FUNC_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };
		String[] arr7 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME1, PERF_VALID_PASSWORD1, SUCCESS_RESPONSE_CODE };

		String[] arr4 = { ENVIRONMENT_PROD, PROD_VALID_USERNAME2, PROD_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr5 = { ENVIRONMENT_FOX7, FOX7_VALID_USERNAME2, FOX7_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr6 = { ENVIRONMENT_FUNC, FUNC_VALID_USERNAME2, FUNC_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		String[] arr8 = { ENVIRONMENT_PERF, PERF_VALID_USERNAME2, PERF_VALID_PASSWORD2, SUCCESS_RESPONSE_CODE };
		
		Object[][] dataSet = new Object[][] { arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8 };
		return Toolbox.returnReducedDataSet(environment, dataSet, testContext.getIncludedGroups(), 1, 2);
	}
	
	
}
