package com.myntra.apiTests.common;

public enum ServiceType
{
	PORTAL_SEARCH,
	PORTAL_SEARCHSERVICE,
	PORTAL_LOYALITY,
	PORTAL_DISCOUNTSERVICE,
	PORTAL_GROUPSERVICE,
	PORTAL_STYLEAPI,
	PORTAL_MAXIMUS,
	ERP_LMS,
	ERP_ATP,
	PORTAL_CART,
	PORTAL_ABSOLUT,
	ERP_MPS,
	PORTAL_TOPNAV,
	PORTAL_MOBILEPDP,
	PORTAL_IDP,
	PORTAL_IDPTELESALES,
	PORTAL_IDEATELESALES,
	PORTAL_NOTIFICATIONS,
	PORTAL_LGPNOTIFICATIONS,
	PORTAL_MOBILEAPPWEBSERVICES,
	PORTAL_MYNTCASHSERVICE,
	PORTAL_CONFIGURATION,
	PORTAL_GIFTCARDSERVICE,
	PORTAL_CONTACTUS,
	PORTAL_GIFTBIGSERVICE,
	PORTAL_TOPNAVCONFIGURATION,
	PORTAL_WALLETSERVICE,
	PORTAL_GIFTCARDNEWSERVICE,
    PORTAL_PHONEPE,
	PORTAL_LOCATION,
	PORTAL_LOOKGOOD,
	PORTAL_BANNER,
	PORTAL_CMSSERVICE,
	ERP_CRMSERVICEPORTAL,
	ERP_CRMSERVICEERP,
	ERP_CRMSERVICERIGHTNOW,
	ERP_SELLERSERVICES,
	PORTAL_CATALOGSERVICE,
	PORTAL_SESSION,
	PORTAL_PAYMENTSERVICE,
	ERP_OMS,
	PORTAL_REQUEST,
	PORTAL_ITEMSCHECKOUTQADONE,
	PORTAL_UPDATEORDERTOWP,
	PORTAL_UPDATEORDERTOCANCELLED,
	PORTAL_DEVAPIS,
	PORTAL_DEVAPISHTTPS,
	PORTAL_DEVAPISNOTIFICATION,
	PORTAL_DEVAPISPROFILEANDPRODUCTS,
	PORTAL_DEVAPISLIKESCOUNT,
	PORTAL_DEVAPILOOKS,
	PORTAL_DEVAPISTYLEFORUM,
	PORTAL_FASHIONCORNERDESTINATION,
	PORTAL_COUPONSERVICE,
	PORTAL_PRICINGENGINECOUPON,
	PORTAL_DEALSSERVICE,
	PORTAL_DOTD,
	PORTAL_MYNTAPI,
	PORTAL_ADDRESSSCOREFG,
	PORTAL_TASKEY,
	PORTAL_WEBHOOK,
	PORTAL_WEBHOOKSLACKCHANNEL,
	PORTAL_ODIN,
	PORTAL_ADDRESSSCORE,
	ERP_MARKETPLACEPARTNERPORTAL,
	ERP_MARKETPLACESCORECARD,
	ERP_MARKETPLACEMANAGEFULFILLMENT,
	ERP_MARKETPLACEVMS,
	ERP_MARKETPLACESELLER,
	ERP_MANUFACTURING,
	ERP_CITRUS,
	ERP_MARKETPLACERMSGATEPASS,
	PORTAL_SESSIONNEW,
	ERP_WMS,
	PORTAL_FASHIONCORNERDESTINATIONMYNTAPI,
	PORTAL_UPSSERVICE,
	FASHIONCORNER_GIVECOMMENTFIRSTTIME,
	FASHIONCORNER_GIVECOMMENT,
	ERP_MARKETPLACEVMSVENDOR,
	ERP_UNICOM,
	PORTAL_PPS,
	PORTAL_PAYU,
	PORTAL_PAYMENTS,
	ERP_SPS,
	PORTAL_FORMDATA,
	PORTAL_FREESHIPPING,
	PORTAL_CATALOGSERVICES,
	PORTAL_UI,
	PORTAL_CHECKOUT,
	PORTAL_UICART,
	PORTAL_SWITCH,
	PORTAL_TESTRAIL,
	//Added for CMS APIs
	CMS_CATALOG,
	CMS_HSN,
	
	// added for idea api
	PORTAL_IDEA,
	
	PORTAL_PARSE,
	PORTAL_ADDRESS,
	PORTAL_CREATESTYLES,
	
	//Template Service
	PORTAL_TEMPLATE,
	
	// added for erp bounty
	ERP_BOUNTY,
	

	// added for erp silkroute
	ERP_SILKROUTE,
	
	PORTAL_INLINECONTENT,
	PORTAL_DISCOUNTSERVICEV2,
	
	//Tagservice
	PORTAL_TAGSERVICE,
	
	LGP_ABTESTSERVICE, PORTAL_PIM,
	ERP_IMS,
	ERP_FKLISTING,
	
	PORTAL_LOYALTYSERVICE,
	PORTAL_CASHBACKSERVICE,

	//PricingPromotion
	PORTAL_PRICINGANALYTICS,
	PORTAL_PRICINGENGINE,
	PORTAL_PRICINGPOLICY,
	PORTAL_FILTEREXCLUSION,
	PORTAL_CREATETDEXCLUSION,
	PORTAL_PRICINGMPSPHASEOUT,
	
	ERP_FLIPKART,
	//Knight Service
	PORTAL_KNIGHTSERVICE, PORTAL_DEVAPIAPPREFERRAL, PORTAL_MAGASIN, LGP_SERVE,PORTAL_NOTIFICATIONASYNC,
	
	//pnp Test Tools
	PORTAL_PNPTESTTOOLS, PORTAL_CARTCOUPON, ERP_RMS, PORTAL_LISTS, LGP_LGPSERVICE,LGP_LGPSERVICEQA, PORTAL_PRICINGPOLICYNEW,LGP_CONTOUR,
	PORTAL_DEVAPISHOTS,LGP_PUMPSSERVICE,LGP_SNSSERVICE, LGP_SESSIONSERVICE,LGP_HALLMARKSERVICE, LGP_NOTIFICATIONRESULTS, LGP_NOTIFICATIONCAPPING, LGP_CAMPAIGNSYSTEMS,
	
	PORTAL_ATS,
	
	//BI
	BI_BISERVICE,BI_UDPSERVICES,
	PORTAL_APIFY;
}
