package com.myntra.apiTests.portalservices.giftcardservice;

/**
 * @author shankara.c
 *
 */
public enum GiftCardServiceEnum 
{
	FOX7_VALID_ORDER_ID,
	
	FOX7_VALID_GIFT_CARD_TYPE1,
	FOX7_VALID_GIFT_CARD_NUMBER1,
	FOX7_VALID_GIFT_CARD_PINCODE1,
	FOX7_VALID_GIFT_CARD_LOGIN1,
	
	FOX7_VALID_GIFT_CARD_TYPE2,
	FOX7_VALID_GIFT_CARD_NUMBER2,
	FOX7_VALID_GIFT_CARD_PINCODE2,
	FOX7_VALID_GIFT_CARD_LOGIN2,
	
	FOX7_VALID_GIFT_CARD_TYPE3,
	FOX7_VALID_GIFT_CARD_NUMBER3,
	FOX7_VALID_GIFT_CARD_PINCODE3,
	FOX7_VALID_GIFT_CARD_LOGIN3,
	
	FOX7_VALID_GIFT_CARD_TYPE4,
	FOX7_VALID_GIFT_CARD_NUMBER4,
	FOX7_VALID_GIFT_CARD_PINCODE4,
	FOX7_VALID_GIFT_CARD_LOGIN4,
	
	FOX7_VALID_GIFT_CARD_TYPE5,
	FOX7_VALID_GIFT_CARD_NUMBER5,
	FOX7_VALID_GIFT_CARD_PINCODE5,
	FOX7_VALID_GIFT_CARD_LOGIN5,
	
    FUNCTIONAL_VALID_ORDER_ID,
	
    FUNCTIONAL_VALID_GIFT_CARD_TYPE1,
    FUNCTIONAL_VALID_GIFT_CARD_NUMBER1,
    FUNCTIONAL_VALID_GIFT_CARD_PINCODE1,
    FUNCTIONAL_VALID_GIFT_CARD_LOGIN1,
	
    FUNCTIONAL_VALID_GIFT_CARD_TYPE2,
    FUNCTIONAL_VALID_GIFT_CARD_NUMBER2,
    FUNCTIONAL_VALID_GIFT_CARD_PINCODE2,
    FUNCTIONAL_VALID_GIFT_CARD_LOGIN2,
	
    FUNCTIONAL_VALID_GIFT_CARD_TYPE3,
    FUNCTIONAL_VALID_GIFT_CARD_NUMBER3,
    FUNCTIONAL_VALID_GIFT_CARD_PINCODE3,
    FUNCTIONAL_VALID_GIFT_CARD_LOGIN3,
	
    FUNCTIONAL_VALID_GIFT_CARD_TYPE4,
    FUNCTIONAL_VALID_GIFT_CARD_NUMBER4,
    FUNCTIONAL_VALID_GIFT_CARD_PINCODE4,
    FUNCTIONAL_VALID_GIFT_CARD_LOGIN4,
	
    FUNCTIONAL_VALID_GIFT_CARD_TYPE5,
    FUNCTIONAL_VALID_GIFT_CARD_NUMBER5,
    FUNCTIONAL_VALID_GIFT_CARD_PINCODE5,
    FUNCTIONAL_VALID_GIFT_CARD_LOGIN5,
	
	GIFT_CARD_AMOUNT,
	
	TOTAL_BILL_AMOUNT1,
	TOTAL_BILL_AMOUNT2,
	TOTAL_BILL_AMOUNT3,
	TOTAL_BILL_AMOUNT4,
	TOTAL_BILL_AMOUNT5,
	
	GETGIFTCARDBAL_SUCCESS_STATUS_CODE,
	GETGIFTCARDBAL_SUCCESS_STATUS_MSG,
	
	GETGIFTCARDAMTFROMORDER_SUCCESS_STATUS_CODE,
	GETGIFTCARDAMTFROMORDER_SUCCESS_STATUS_MSG,
	
	REDEEMGIFTCARD_SUCCESS_STATUS_CODE,
	REDEEMGIFTCARD_SUCCESS_STATUS_MSG,

	CANCELREDEEMGIFTCARD_SUCCESS_STATUS_CODE,
	CANCELREDEEMGIFTCARD_SUCCESS_STATUS_MSG,
	
	ORDERSTATUS_SUCCESS_STATUS_CODE,
	ORDERSTATUS_SUCCESS_STATUS_MSG,
	
	FAILURE_STATUS_CODE,
	FAILURE_STATUS_MSG,

	GETGIFTCARDBAL_FAILURE_STATUS_CODE1,
	GETGIFTCARDBAL_FAILURE_STATUS_MSG1,
	
	GETGIFTCARDBAL_FAILURE_STATUS_CODE2,
	GETGIFTCARDBAL_FAILURE_STATUS_MSG2,
	
	GETGIFTCARDBAL_FAILURE_STATUS_CODE3, 
	GETGIFTCARDBAL_FAILURE_STATUS_MSG3,
	
	REDEEMGIFTCARD_FAILURE_STATUS_CODE1,
	REDEEMGIFTCARD_FAILURE_STATUS_MSG1,
	
	REDEEMGIFTCARD_FAILURE_STATUS_CODE2,
	REDEEMGIFTCARD_FAILURE_STATUS_MSG2,
	
	ORDERSTATUS_FAILURE_STATUS_CODE,
	ORDERSTATUS_FAILURE_STATUS_MSG;
}
