package com.myntra.qnotifications;

import org.testng.ITestContext;
import org.testng.annotations.DataProvider;

import com.myntra.lordoftherings.Toolbox;

public class CRMNotifyCodesNotificationsDP {
	
	 @DataProvider
	    public static Object[][] notificationpayloads(ITestContext testContext)
	    {
	        /*Object [] arr1 = {false,"ORDER_CONFIRMED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr2 = {false,"SHIPPED_TO_DC","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>SHIPPED_TO_DC</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr3 = {false,"OUT_FOR_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr4 = {false,"OUT_FOR_DELIVERY_COD","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY_COD</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr5 = {false,"DELAYED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr6 = {true,"FAILED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>FAILED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr7 = {true,"DELIVERED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        */
	        
	       /* Object [] arr1 = {false,"ORDER_CONFIRMED_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr2 = {false,"SHIPPED_TO_DC_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>SHIPPED_TO_DC</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr3 = {false,"OUT_FOR_DELIVERY_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr4 = {false,"OUT_FOR_DELIVERY_COD_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY_COD</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr5 = {true,"DELAYED_DELIVERY_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr6 = {true,"FAILED_DELIVERY_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>FAILED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr7 = {true,"DELIVERED_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
*/
			Object [] arr1 = {true,"ORDER_CONFIRMED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
			Object [] arr2 = {true,"SHIPPED_TO_DC","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>SHIPPED_TO_DC</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
			Object [] arr3 = {true,"OUT_FOR_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
			Object [] arr4 = {true,"OUT_FOR_DELIVERY_COD","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY_COD</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
			Object [] arr5 = {true,"DELAYED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
			Object [] arr6 = {true,"FAILED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>FAILED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
			Object [] arr7 = {true,"DELIVERED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};

			Object [][] dataSet = new Object [][] {arr1,arr2,arr3,arr4,arr5,arr6,arr7};
	        return Toolbox.returnReducedDataSet(dataSet, testContext.getIncludedGroups(),dataSet.length , dataSet.length);
	    }

	@DataProvider
	public static Object[][] differentEmailID(ITestContext testContext)
	{
	        /*Object [] arr1 = {false,"ORDER_CONFIRMED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr2 = {false,"SHIPPED_TO_DC","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>SHIPPED_TO_DC</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr3 = {false,"OUT_FOR_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr4 = {false,"OUT_FOR_DELIVERY_COD","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY_COD</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr5 = {false,"DELAYED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr6 = {true,"FAILED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>FAILED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr7 = {true,"DELIVERED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        */

	       /* Object [] arr1 = {false,"ORDER_CONFIRMED_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr2 = {false,"SHIPPED_TO_DC_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>SHIPPED_TO_DC</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr3 = {false,"OUT_FOR_DELIVERY_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr4 = {false,"OUT_FOR_DELIVERY_COD_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY_COD</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr5 = {true,"DELAYED_DELIVERY_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr6 = {true,"FAILED_DELIVERY_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>FAILED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr7 = {true,"DELIVERED_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
*/
		Object [] arr1 = {"all","ORDER_CONFIRMED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><templateEntry><renderPair><renderKey>entry</renderKey><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents></renderPair></templateEntry>"};
		Object [] arr2 = {"all","SHIPPED_TO_DC","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><templateEntry><renderPair><renderKey>entry</renderKey><notifyEvents><notifyCode>SHIPPED_TO_DC</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents></renderPair></templateEntry>"};
		Object [] arr3 = {"all","OUT_FOR_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><templateEntry><renderPair><renderKey>entry</renderKey><notifyEvents><notifyCode>OUT_FOR_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents></renderPair></templateEntry>"};
		Object [] arr4 = {"all","OUT_FOR_DELIVERY_COD","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><templateEntry><renderPair><renderKey>entry</renderKey><notifyEvents><notifyCode>OUT_FOR_DELIVERY_COD</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents></renderPair></templateEntry>"};
		Object [] arr5 = {"myntra","DELAYED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><templateEntry><renderPair><renderKey>entry</renderKey><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>sneha.agarwal@myntra.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents></renderPair></templateEntry>"};
		Object [] arr6 = {"myntra","FAILED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><templateEntry><renderPair><renderKey>entry</renderKey><notifyEvents><notifyCode>FAILED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>sneha.agarwal@myntra.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents></renderPair></templateEntry>"};
		Object [] arr7 = {"myntra","DELIVERED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><templateEntry><renderPair><renderKey>entry</renderKey><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>sneha.agarwal@myntra.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents></renderPair></templateEntry>"};

		Object [][] dataSet = new Object [][] {arr1,arr2,arr3,arr4,arr5,arr6,arr7};
		return Toolbox.returnReducedDataSet(dataSet, testContext.getIncludedGroups(),dataSet.length , dataSet.length);
	}

	public static String[][] notificationpayloads()
	{
	        /*Object [] arr1 = {false,"ORDER_CONFIRMED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr2 = {false,"SHIPPED_TO_DC","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>SHIPPED_TO_DC</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr3 = {false,"OUT_FOR_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr4 = {false,"OUT_FOR_DELIVERY_COD","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY_COD</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr5 = {false,"DELAYED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr6 = {true,"FAILED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>FAILED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        Object [] arr7 = {true,"DELIVERED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70115495</orderId><releaseId>70115495</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000180808</trackingNo></notifyEvents>"};
	        */

	       /* Object [] arr1 = {false,"ORDER_CONFIRMED_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr2 = {false,"SHIPPED_TO_DC_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>SHIPPED_TO_DC</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr3 = {false,"OUT_FOR_DELIVERY_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr4 = {false,"OUT_FOR_DELIVERY_COD_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY_COD</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr5 = {true,"DELAYED_DELIVERY_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr6 = {true,"FAILED_DELIVERY_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>FAILED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
	        Object [] arr7 = {true,"DELIVERED_MultipleQTY_NotMigrated","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
*/
		String [] arr1 = {"true","ORDER_CONFIRMED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String [] arr2 = {"true","SHIPPED_TO_DC","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>SHIPPED_TO_DC</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String [] arr3 = {"true","OUT_FOR_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String [] arr4 = {"true","OUT_FOR_DELIVERY_COD","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY_COD</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String [] arr5 = {"true","DELAYED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String [] arr6 = {"true","FAILED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>FAILED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String [] arr7 = {"true","DELIVERED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String [][] dataSet;
		dataSet = new String [][] {arr1,arr2,arr3,arr4,arr5,arr6,arr7};
		return dataSet;
	}

	public static String[][] differentEmailID() {
		String[] arr1 = {"all", "ORDER_CONFIRMED", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String[] arr2 = {"all", "SHIPPED_TO_DC", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>SHIPPED_TO_DC</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String[] arr3 = {"all", "OUT_FOR_DELIVERY", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String[] arr4 = {"all", "OUT_FOR_DELIVERY_COD", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>OUT_FOR_DELIVERY_COD</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String[] arr5 = {"myntra", "DELAYED_DELIVERY", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>sneha.agarwal@myntra.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String[] arr6 = {"myntra", "FAILED_DELIVERY", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>FAILED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>sneha.agarwal@myntra.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String[] arr7 = {"myntra", "DELIVERED", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70116140</orderId><releaseId>70116140</releaseId><login>sneha.agarwal@myntra.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>sneha.agarwal@myntra.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String[][] dataSet = new String[][] {arr1, arr2, arr3, arr4, arr5, arr6, arr7};
		return dataSet;
	}

	public static String[][] NPSToggle() {
		String[] arr1 = {"true", "ORDER_CONFIRMED", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>ORDER_CONFIRMED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String [] arr2 = {"true","DELAYED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELAYED_DELIVERY</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String [] arr3 = {"true","DELIVERED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><notifyCode>DELIVERED</notifyCode><islastOrder>false</islastOrder><ispartOrder>false</ispartOrder><customerName>Sneha  Agarwal</customerName><orderId>70139766</orderId><releaseId>70139766</releaseId><login>end2endautomation4@gmail.com</login><address>Testing team  Myntra, Bangalore, KA, India, 560068</address><mobile>8088566581</mobile><email>end2endautomation4@gmail.com</email><cardPaymentEnabled>false</cardPaymentEnabled><actualPromiseTime>16 Dec 2015</actualPromiseTime><trackingNo>ML0000182252</trackingNo></notifyEvents>"};
		String[][] dataSet = new String[][] {arr1, arr2, arr3};
		return dataSet;
	}

	public static String[][] UnknownNotification() {
		String[] arr1 = {"false", "CONFIRMED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><eventKey>CONFIRMED</eventKey><data><entry><key>orderId</key><value>79900370</value></entry></data></notifyEvents>"};
        String[] arr2 = {"false", "DELAYED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><eventKey>DELAYED</eventKey><data><entry><key>orderId</key><value>79900370</value></entry></data></notifyEvents>"};
        String[] arr3 = {"false", "RANDOM","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><eventKey>RANDOM</eventKey><data><entry><key>orderId</key><value>79900370</value></entry></data></notifyEvents>"};

        String[][] dataSet = new String[][] {arr1, arr2, arr3};
		return dataSet;
	}

    public static String[][] verifyIdempotency() {
        String[] arr1 = {"true", "ORDER_CONFIRMED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><eventKey>ORDER_CONFIRMED</eventKey><idempotencyKey>snbcdef#@</idempotencyKey><data><entry><key>orderId</key><value>70139766</value></entry></data></notifyEvents>"};
        String[] arr2 = {"true", "DELAYED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><eventKey>DELAYED_DELIVERY</eventKey><idempotencyKey>snbcde123456</idempotencyKey><data><entry><key>releaseId</key><value>70139766</value></entry></data></notifyEvents>"};
        String[] arr3 = {"true", "DELIVERED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><eventKey>DELIVERED</eventKey><idempotencyKey>1234567890#@</idempotencyKey><data><entry><key>releaseId</key><value>70139766</value></entry></data></notifyEvents>"};
		String[] arr4 = {"false", "ORDER_CONFIRMED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><eventKey>ORDER_CONFIRMED</eventKey><idempotencyKey>snbcdef#@</idempotencyKey><data><entry><key>orderId</key><value>70139766</value></entry></data></notifyEvents>"};
		String[] arr5 = {"false", "DELAYED_DELIVERY","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><eventKey>DELAYED_DELIVERY</eventKey><idempotencyKey>snbcde123456</idempotencyKey><data><entry><key>releaseId</key><value>70139766</value></entry></data></notifyEvents>"};
		String[] arr6 = {"false", "DELIVERED","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><notifyEvents><eventKey>DELIVERED</eventKey><idempotencyKey>1234567890#@</idempotencyKey><data><entry><key>releaseId</key><value>70139766</value></entry></data></notifyEvents>"};
		String[][] dataSet = new String[][] {arr1, arr2, arr3,arr4,arr5,arr6};
        return dataSet;
    }

}
