package com.myntra.apiTests.portalservices.ideaapi;

/**
 * @author shankara.c
 *
 */
public enum IdeaErrorCodes 
{
	UNAUTHORIZED_OPERATION(110001, "UNAUTHORIZED_OPERATION"),

	LOGIN_INVALID_CREDENTIALS(110002, "LOGIN_INVALID_CREDENTIALS"),

	SIGNUP_USER_EXISTS(110003, "SIGNUP_USER_EXISTS"),

	SIGNUP_FIELDS_EMPTY_MISSING(110004, "SIGNUP_FIELDS_EMPTY_MISSING"),

	INTERNAL_SERVER_ERROR(110010, "INTERNAL_SERVER_ERROR"),

	FBLOGIN_ERROR(110011, "FBLOGIN_ERROR"),

	FBLOGIN_TOKEN_MISSING(110012, "FBLOGIN_TOKEN_MISSING"),

	FBLOGIN_TOKEN_INVALID(110013, "FBLOGIN_TOKEN_INVALID"),

	FORGOT_LOGIN_INVALID(110014, "FORGOT_LOGIN_MISSING"),

	FORGOT_LOGIN_NOT_REGISTERED(110015, "FORGOT_LOGIN_NOT_REGISTERED"),

	FORGOT_RESET_INVALID_ENTRY(110016, "FORGOT_RESET_INVALID_ENTRY"),

	FORGOT_RESET_INVALID_TOKEN(110017, "FORGOT_RESET_INVALID_TOKEN"),

	INVALID_CAPTCHA_VALUE(110018, "INVALID_CAPTCHA_VALUE"),
	
	ACCOUNT_DELETED(111001, "ACCOUNT_DELETED"),

	ACCOUNT_EXPIRED(111002, "ACCOUNT_EXPIRED"),

	ACCOUNT_LOCKED(111003, "ACCOUNT_LOCKED"),

	ACCOUNT_DOES_NOT_EXISTS(111004, "ACCOUNT_DOES_NOT_EXISTS"),

	REGISTRATION_FAILED(111010, "REGISTRATION_FAILED"),

	AUTHENTICATION_FAILED(111011, "AUTHENTICATION_FAILED"),

	INVALID_EMAIL(111012, "INVALID_EMAIL"),

	INVALID_PHONENO(111013, "INVALID_PHONENO"),

	EMAIL_ALREADY_EXISTS(111014, "EMAIL_ALREADY_EXISTS"),

	INVALID_REGISTRATION_CHANNEL(111015, "INVALID_REGISTRATION_CHANNEL"),

	GPLOGIN_ERROR(111016, "GPLOGIN_ERROR"),

	GPLOGIN_TOKEN_MISSING(111017, "GPLOGIN_TOKEN_MISSING"),

	GPLOGIN_TOKEN_INVALID(111018, "GPLOGIN_TOKEN_INVALID"),

	PHONE_ALREADY_EXISTS(111019, "PHONE_ALREADY_EXISTS"),

	INVALID_APP(111020, "INVALID_APP"),

	ACCOUNT_RECOVERY(111021, "ACCOUNT_RECOVERY"),

	INVALID_REFRESH_TOKEN(111022, "INVALID_REFRESH_TOKEN"),

	INVALID_OTP_TOKEN(111023, "INVALID_OTP_TOKEN"),

	INVALID_PASSWORD_FORMAT(112000, "INVALID_PASSWORD_FORMAT");
	
	private int ideaErrorCode;
	
	private String ideaErrorMsg;
	
	private IdeaErrorCodes(int paramErrorCode, String paramErrorMsg)
	{
		this.ideaErrorCode = paramErrorCode;
		this.ideaErrorMsg = paramErrorMsg;
	}
	
	public int getIdeaErrorCode() {
		return ideaErrorCode;
	}
	
	public String getIdeaErrorMsg() {
		return ideaErrorMsg;
	}
}
