/**
 * 
 */
package com.myntra.apiTests.portalservices.idpservice;

/**
 * @author shankara.c
 *
 */
public enum IDPServiceDataProviderEnum 
{
	// ENVIRONMENTS
	ENVIRONMENT,
	ENVIRONMENT_PROD,
	ENVIRONMENT_FOX7,
	ENVIRONMENT_FOX8,
	ENVIRONMENT_FUNC,
	ENVIRONMENT_DELTA7,
	ENVIRONMENT_DELTA7_OMS,
	ENVIRONMENT_DELTA7_WMS,
	ENVIRONMENT_DELTA7_ATP,
	ENVIRONMENT_PERF,

	// PROD ENV RELATED
	PROD_VALID_USERNAME1,
	PROD_VALID_PASSWORD1,
	PROD_VALID_USERNAME2,
	PROD_VALID_PASSWORD2,
	PROD_INVALID_USERNAME1,
	PROD_INVALID_PASSWORD1,
	PROD_INVALID_USERNAME2,
	PROD_INVALID_PASSWORD2,
	
	// FOX7 ENV RELATED
	FOX7_VALID_USERNAME1,
	FOX7_VALID_PASSWORD1,
	FOX7_VALID_USERNAME2,
	FOX7_VALID_PASSWORD2,
	FOX7_INVALID_USERNAME1,
	FOX7_INVALID_PASSWORD1,
	FOX7_INVALID_USERNAME2,
	FOX7_INVALID_PASSWORD2,

	// FUNC ENV RELATED
	FUNC_VALID_USERNAME1,
	FUNC_VALID_PASSWORD1,
	FUNC_VALID_USERNAME2,
	FUNC_VALID_PASSWORD2,
	FUNC_INVALID_USERNAME1,
	FUNC_INVALID_PASSWORD1,
	FUNC_INVALID_USERNAME2,
	FUNC_INVALID_PASSWORD2,

	// PERF ENV RELATED
	PERF_VALID_USERNAME1,
	PERF_VALID_PASSWORD1,
	PERF_VALID_USERNAME2,
	PERF_VALID_PASSWORD2,
	PERF_INVALID_USERNAME1,
	PERF_INVALID_PASSWORD1,
	PERF_INVALID_USERNAME2,
	PERF_INVALID_PASSWORD2,
	
	// SUCCESS RELATED
	SUCCESS_RESP_CODE,
	SUCCESS_STATUS_CODE,
	SUCCESS_STATUS_MSG,
	SUCCESS_STATUS_TYPE,
	VALID_MOBILE_LENGTH,
	
	// FAILURE RELATED
	SIGNIN_FAILURE_STATUS_CODE,
	SIGNIN_FAILURE_STATUS_MSG,
	FAILURE_STATUS_TYPE,
	SIGNUP_FAILURE_STATUS_CODE1,
	SIGNUP_FAILURE_STATUS_MSG1,
	SIGNUP_EMPTY_LOGINID,
	SIGNUP_FAILURE_STATUS_CODE2,
	SIGNUP_FAILURE_STATUS_MSG2,
	NULL_VALUE,
	FP_ERROR_STATUS_CODE1,
	FP_ERROR_STATUS_MSG1,
	FP_ERROR_STATUS_CODE2,
	FP_ERROR_STATUS_MSG2,
	PROD_RP_VALID_USERNAME,
	PROD_RP_VALID_PASSWORD,
	FOX7_RP_VALID_USERNAME,
	FOX7_RP_VALID_PASSWORD,
	FUNC_RP_VALID_USERNAME,
	FUNC_RP_VALID_PASSWORD,
	PERF_RP_VALID_USERNAME,
	PERF_RP_VALID_PASSWORD,
	RP_ERROR_STATUS_CODE1,
	RP_ERROR_STATUS_MSG1,
	RP_ERROR_STATUS_CODE2,
	RP_ERROR_STATUS_MSG2,
	
	// SIGNUP API RELTED DATA
	SIGNUP_FIRST_NAME,
	SIGNUP_LAST_NAME,
	SIGNUP_MYNT_DOMAIN,
	SIGNUP_GMAIL_DOMAIN,
	SIGNUP_PASSWORD1,
	SIGNUP_PASSWORD2, 
	SIGNUP_USER_TYPE,
	SIGNUP_GENDER_MALE,
	SIGNUP_GENDER_FEMALE,
	SIGNUP_TITLE_MR,
	SIGNUP_TITLE_MRS,
	SIGNUP_MOBILE_NUMBER;
}
