package com.myntra.apiTests.portalservices.notificationservice;

/**
 * @author shankara.c
 *
 */
public enum NotificationServiceEnum 
{
	// Notification Types
	NOTIFICATION_TYPE_MARKETING,
	NOTIFICATION_TYPE_REVENUE_LABS,
	NOTIFICATION_TYPE_ORDER_STATUS_CHANGE,
	NOTIFICATION_TYPE_PRICE_CHANGE,
	
	// Portal groups
	PORTAL_GROUP_MYNTRA,
	PORTAL_GROUP_MY_URBAN_LOOK,
	PORTAL_GROUP_GAP,
	PORTAL_GROUP_PUMA,
	PORTAL_GROUP_LEVIS,
	
	ACTION_DELETE,

	// UserIds
	PROD_VALID_USER_ID,
	FOX7_VALID_USER_ID,
	FUNC_VALID_USER_ID,
	PERF_VALID_USER_ID,
	
	PROD_VALID_USER_IDS,
	FOX7_VALID_USER_IDS,
	FUNC_VALID_USER_IDS,
	PERF_VALID_USER_IDS,
	
	TITAN_PROD_NOTIFICATION_TEXT,
	TITAN_PROD_NOTIFICATION_TITLE,
	TITAN_PROD_NOTIFICATION_IMG_URL,
	TITAN_PROD_NOTIFICATION_PAGE_URL,

	FOSSIL_PROD_NOTIFICATION_TEXT,
	FOSSIL_PROD_NOTIFICATION_TITLE,
	FOSSIL_PROD_NOTIFICATION_IMG_URL,
	FOSSIL_PROD_NOTIFICATION_PAGE_URL,

	CAT_PROD_NOTIFICATION_TEXT,
	CAT_PROD_NOTIFICATION_TITLE,
	CAT_PROD_NOTIFICATION_IMG_URL,
	CAT_PROD_NOTIFICATION_PAGE_URL,

	VEROMODA_PROD_NOTIFICATION_TEXT,
	VEROMODA_PROD_NOTIFICATION_TITLE,
	VEROMODA_PROD_NOTIFICATION_IMG_URL,
	VEROMODA_PROD_NOTIFICATION_PAGE_URL,

	PUMA_PROD_NOTIFICATION_TEXT,
	PUMA_PROD_NOTIFICATION_TITLE,
	PUMA_PROD_NOTIFICATION_IMG_URL,
	PUMA_PROD_NOTIFICATION_PAGE_URL,

	NIKE_PROD_NOTIFICATION_TEXT,
	NIKE_PROD_NOTIFICATION_TITLE,
	NIKE_PROD_NOTIFICATION_IMG_URL,
	NIKE_PROD_NOTIFICATION_PAGE_URL,

	ADIDAS_PROD_NOTIFICATION_TEXT,
	ADIDAS_PROD_NOTIFICATION_TITLE,
	ADIDAS_PROD_NOTIFICATION_IMG_URL,
	ADIDAS_PROD_NOTIFICATION_PAGE_URL,
	
}
